<a href="https://colab.research.google.com/github/teamProjectIti/tf_Keras/blob/main/Pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.8.0+cu126


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
 scalar.item()

7

In [5]:
 vector=torch.tensor([7,7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
 vector[0]

tensor(7)

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
# tensor

tensor=torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [14]:
tensor.ndim

4

In [15]:
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

random tensor

In [16]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5802, 0.7527, 0.8130, 0.8516],
        [0.3204, 0.4390, 0.3953, 0.8836],
        [0.2887, 0.0234, 0.2627, 0.2996]])

In [17]:
random_tensor_2=torch.rand(5,2)
random_tensor_2

tensor([[0.3329, 0.8812],
        [0.6348, 0.5193],
        [0.6428, 0.4761],
        [0.8979, 0.5392],
        [0.2876, 0.7246]])

In [18]:
random_tensor_3=torch.rand(10,5)
random_tensor_3

tensor([[0.9745, 0.7577, 0.6502, 0.0405, 0.7328],
        [0.3741, 0.9001, 0.3459, 0.9056, 0.6701],
        [0.0457, 0.7687, 0.9706, 0.6171, 0.9258],
        [0.0712, 0.4790, 0.6089, 0.0426, 0.3232],
        [0.4804, 0.3563, 0.1825, 0.2965, 0.3338],
        [0.3052, 0.5672, 0.7043, 0.8161, 0.6795],
        [0.9959, 0.2429, 0.9267, 0.1862, 0.1217],
        [0.3718, 0.3300, 0.2552, 0.7327, 0.0346],
        [0.3613, 0.6020, 0.0523, 0.8423, 0.6888],
        [0.2335, 0.5184, 0.9748, 0.3204, 0.6412]])

In [19]:
random_tensor_4=torch.rand(3,2,2)
random_tensor_4

tensor([[[0.9446, 0.3547],
         [0.5442, 0.3564]],

        [[0.1255, 0.5648],
         [0.4747, 0.2214]],

        [[0.3986, 0.8295],
         [0.6355, 0.4326]]])

tensor shape image

In [20]:
ransom_tensor_image=torch.rand(size=(224,224,3)) # h,w,colour
ransom_tensor_image.shape,ransom_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
ransom_tensor_image

tensor([[[3.8242e-01, 4.1012e-01, 2.9138e-01],
         [4.2317e-01, 5.6432e-01, 8.6283e-01],
         [3.5475e-02, 8.2011e-01, 1.4490e-01],
         ...,
         [2.0565e-01, 1.5042e-01, 6.6213e-01],
         [5.5028e-01, 6.7443e-02, 5.0805e-01],
         [2.0201e-01, 1.7968e-01, 7.8378e-01]],

        [[9.6091e-01, 8.7036e-01, 9.9919e-01],
         [8.8958e-01, 3.8511e-01, 8.4428e-01],
         [2.2530e-02, 6.9828e-01, 4.7760e-01],
         ...,
         [1.5195e-01, 5.8665e-01, 5.5719e-01],
         [8.9269e-01, 8.0958e-01, 6.6666e-01],
         [3.8485e-01, 2.5300e-02, 5.4634e-02]],

        [[1.6555e-01, 9.4175e-01, 7.9412e-01],
         [5.8166e-01, 7.2609e-01, 9.2374e-01],
         [9.6607e-01, 4.8685e-01, 4.7608e-01],
         ...,
         [8.3429e-01, 1.2837e-01, 9.9754e-01],
         [9.3438e-01, 2.8553e-01, 9.2102e-02],
         [2.9226e-01, 1.9104e-01, 9.2348e-01]],

        ...,

        [[4.0952e-01, 8.6987e-01, 6.0033e-01],
         [6.4067e-01, 3.3307e-01, 5.0822e-01]

In [22]:
import torch
import matplotlib.pyplot as plt

# Create random tensor image
random_tensor_image = torch.rand(size=(224, 224, 3))  # (H, W, C)

# Show shape and dimensions
print(random_tensor_image.shape, random_tensor_image.ndim)

# Display the image
plt.imshow(random_tensor_image)
plt.title("Random Tensor Image")
plt.axis("off")  # hides axes
plt.show()


torch.Size([224, 224, 3]) 3


In [23]:
rt=torch.rand(3,4)
rt

tensor([[0.4647, 0.1049, 0.0880, 0.3595],
        [0.4510, 0.4045, 0.2340, 0.5795],
        [0.8228, 0.2444, 0.9169, 0.6022]])

In [24]:
 rt=torch.rand(3,4,dtype=torch.double)
rt

tensor([[0.5185, 0.6341, 0.5091, 0.5119],
        [0.6308, 0.8251, 0.4002, 0.2871],
        [0.8016, 0.5418, 0.6834, 0.0402]], dtype=torch.float64)

In [25]:
zeorRt=torch.zeros(3,4)
zeorRt

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
onRT=torch.ones(3,4)
onRT

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
 # من 0 إلى 1000 بخطوة قدرها 77
tensor2 = torch.arange(start=0, end=1000, step=77)
print(tensor2)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [28]:
tensor3 = torch.arange(1, 10)
print(tensor3)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
# تنسور أصلي
tensor_base = torch.arange(1, 11)  # [1,2,...,10]
tensor_base
# تنسور أصفار بنفس الشكل
tensor_zeros = torch.zeros_like(tensor_base)
print(tensor_zeros)


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [30]:
tensor_ones = torch.ones_like(tensor_base)
print(tensor_ones)


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [31]:
data=torch.range(0,10)
data

/tmp/ipython-input-3204747829.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  data=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
torch.__version__

'2.8.0+cu126'

In [33]:
one_data= torch.arange(start=1,end=10,step=1)
one_data

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
int_32_tensor= torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor=torch.tensor([3.6,6.0,6.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3.6000, 6.0000, 6.0000])

In [37]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5996, 6.0000, 6.0000], dtype=torch.float16)

In [38]:
res=float_16_tensor* float_32_tensor
res

tensor([12.9586, 36.0000, 36.0000])

In [39]:
float_32_tensor* int_32_tensor

tensor([10.8000, 36.0000, 54.0000])

In [40]:
 some_tensor=torch.rand(3,4)
 some_tensor

tensor([[0.9653, 0.0491, 0.0363, 0.3080],
        [0.7889, 0.9849, 0.5448, 0.2014],
        [0.9699, 0.6563, 0.3583, 0.6291]])

In [45]:
some_tensor.shape
some_tensor.dtype
some_tensor.size
some_tensor.device

device(type='cpu')

In [46]:
tensor=torch.tensor([1,2,30])
tensor+10

tensor([11, 12, 40])

In [47]:
tensor*10

tensor([ 10,  20, 300])

In [48]:
tensor-10

tensor([-9, -8, 20])

In [49]:
torch.mul(tensor,10)

tensor([ 10,  20, 300])

In [50]:
torch.add(tensor,10)

tensor([11, 12, 40])